# Generated by Django 4.2.2 on 2023-06-28 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('compact', 'Compact'), ('premium', 'Premium'), ('minivan', 'Minivan')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('rental_datetime', models.DateTimeField()),
                ('car_mileage', models.IntegerField()),
                ('car_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.carcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_datetime', models.DateTimeField()),
                ('mileage_at_return', models.IntegerField()),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.rental')),
            ],
        ),
    ]
