# Generated by Django 4.2.2 on 2023-06-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_booking_remove_return_rental_delete_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_mileage_at_pickup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car_mileage_at_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
