# Generated by Django 4.2.2 on 2023-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_booking_car_mileage_at_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Total Car Booking Amount'),
        ),
    ]
