# Generated by Django 4.2.2 on 2023-06-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rental_datetime',
            field=models.DateTimeField(help_text='Format yyyy-mm-dd hh:mm::ss'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_datetime',
            field=models.DateTimeField(blank=True, help_text='Format yyyy-mm-dd hh:mm::ss', null=True),
        ),
    ]
